### PR TITLE
Update Skins.lua

### PR DESCRIPTION
**Pull request by TheNeoTV**
Fix an issue when opening settings!

### CODE REVIEW

**Comment by StormFX** [comment]
This has already been list as an issue with the fix mentioned here. It will be handled in the next update.

**Comment by TheNeoTV** [comment]
Duplicate? You add a "Duplicate" of an Pullrequest to Fix this?! Ähm okay !

**Comment by StormFX** [comment]
Because it _is_ a duplicate of issue #80.

**Comment by TheNeoTV** [comment]
It is a FIX not a Duplicate?! Really you should READ before Post!

**Comment by StormFX** [comment]
You submitted a pull request for an issue that was already submitted and set to be addressed. That qualifies as a the issue being reported twice, ergo a "duplicate". Also:

> Pull requests are only accepted for localization updates. All other submissions must be made via the issue tracker.

https://github.com/StormFX/Masque/blob/master/CONTRIBUTING.md

**Pull request closed without merging**
